version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    container_name: sanJorgeDb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build: .
    command: uvicorn main:app  --host=0.0.0.0  --port=80 --reload
    ports:
      - 8090:80
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/app

volumes:
  mysql-data: